import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <form action="http://localhost:9000/asr?task=transcribe&language=en" method="POST" encType='multipart/form-data'>
          <input type="file" name="audio_file" accept='audio/*'/>
          <button type="submit">Submit</button>
        </form> */}
      </main>
    </>
  )
}
